ExplodingMobs:
  Enabled: false
  Radius: 16
  Fire: true
  Areas:
    - 3000,5,3000 3100,5,3100

PlayerLog:
  Enabled: true

SleepOnHalf:
  Enabled: true
  Ratio: 50
  
EnvironmentMods:
  BlockIronGolems: true
  BlockVillagerTrades: true
  ModifyTraderTrades: true
  BlockMobFallDamage: true
  CreeperBuff:
    FuseTicks: 30
    DamageRadius: 3

Items:
  MendingNetherite: true
  BlockMending: true

FastCarts:
  Enabled: true
  Speed: 0.4


