name: GoldenWind
main: org.ludin.GoldenWind.Main
version: 0.1
author: sludin
api-version: 1.16
commands:
  gw:
    description: GoldenWind server command
    usage: /gw
    permission: GoldenWind.gw
    permission-message: You don't have <permission>
  goldenwind:
    description: GoldenWind server command
    usage: /goldenwind
    permission: GoldenWind.goldenwind
    permission-message: You don't have <permission>
